### PR TITLE
Swe55 course template editor scroll fix

### LINKED ISSUE #55: Course Template Editor Scroll Issue
## Issue Description
After creating a course and navigating to it through the course list, if the template has too many rows, the template overflows below the footer, and there is no way to scroll.

Ideally, a course with many rows should be scaled in such a way that the template appears entirely in the current view. In other words, the template should be made to fit the view without the need for scrollbars.

## Steps to Reproduce
- Create a new course with a larger number of rows (around 20)
- Navigate to the template editor by clicking the new course in the course list
- Observe that the template overflows and has no scroll bars.

## Tasks
- [x] Determine the root cause of the issue
- [x] Modify the template so that it is made to fit the view
- [ ] Write tests

## Screenshots and Documentation
image

### PR DESCRIPTION
**Pull request by brandon1024**
### Changes Proposed in this Pull Request:
- Made UI modifications to fix scrolling, the courselist border issue
- Improved the seat grid to make it fit to the size of the screen dynamically

### On Develop
image

#### Large Screen (w/ 15x15 grid)
image

#### Small Screen  (w/ 15x15 grid)
image

#### Large Screen (w/ 5x5 grid)
image

#### Small Screen  (w/ 5x5 grid)
image

### CODE REVIEW

**Comment by brandon1024** [comment]
Added a change to ensure grid cells have a minimum size of 80px by 30px.

image

**Comment by mwalz1** [comment]
Looks good so far guys!  What I am going to do right now is reach out to Dr. McIsaac and see if she has any specifications on how she wants the larger tables to be displayed.  Will keep you all updated.

**Review by mwalz1 — APPROVED** [review]
Everything aligns well with Dr. MacIsaac's requirements.
Something to keep in mind for future development is that no font should ever get smaller than 9points.

**Review by jsmith — APPROVED** [review]
Nice changes, approved!

**Pull request merged**
