### PR TITLE
Adding testuser to database

### PR DESCRIPTION
**Pull request by dsteen338**
## Fixes #
No issue related.
### Changes Proposed in this Pull Request:
- Added default user "testuser" with password "password" for development

### Additional Comments and Documentation:
I could also add a default course or anyhing else to this script, and I could put this into its own folder if others think that's a good idea.

### CODE REVIEW

**Comment by brandon1024** [comment]
I like this. How do we use it? Just run the script?

**Comment by brandon1024** [comment]
Looks good to me. If someone signs off on this, it can be merged in.

**Review by brandon1024 — APPROVED** [review]
:+1:

**Comment by jsmith** [comment]
Signed off & merged!

**Pull request merged**
