### PR TITLE
Spring Boot & Maven Project Init

### PR DESCRIPTION
**Pull request by jsmith**
Initialized a Spring/Maven project using the Spring Initializer. I'm not entirely sure the setup process for importing a new project in Idea but it should go something like this:

1. Clone the repository `$ git clone -b SWE-Project-Initialization https://github.com/SWE-4103-Group-3/Project.git` into wherever you're keeping your projects. For me, it was `C:\Users\jasmi\IdeaProjects`
2. In the IDEA [startup window](https://www.jetbrains.com/help/img/idea/2017.2/ideaWelcomeScreen.png), choose `Import Project`
3. Choose the folder that you cloned & hit `ok`
4. In the new window, make sure `Import project from external model` is selected and choose `Maven`
5. Click next until you are through the setup process & then click `Finish` (make sure your JDK is selected when it asks)
4. To run, open `TrackerApplication.java`, right-click in the text editor & click `Run 'TrackerApplication.java'`
5. You should now be able to go to `localhost:8080`

### CODE REVIEW

**Review by dsteen338 — APPROVED** [review]
Setup looks good to me.

**Comment by tonerm43** [comment]
This looks good to me :+1:  Has anyone tested locally?

**Comment by brandon1024** [comment]
Has anyone had any luck running this locally on their machine? I am not able to figure it out.

**Comment by jsmith** [comment]
Where exactly is the problem? I haven't actually tested the instructions so I want to make sure they are correct!

**Comment by dsteen338** [comment]
I added the project directly from github in Intellij and it seemed fine, just trying to figure out stuff with my Java install and stuff now....

**Comment by brandon1024** [comment]
@jacsmith21 I cloned the repo and pulled down your branch, but I can't seem to figure out how to run 'TrackerApplication.java'.

At any rate, we should make sure that people are able to get this running locally before we merge. If anyone figures it out, lets write a bit of documentation to help others. It might have something to do with properly setting up dependencies.

**Comment by jsmith** [comment]
Yeah, I don't want it to be merged until the instructions are all there. I'll see what I can do

**Comment by dsteen338** [comment]
I've got it running on mine, working through it with mac right now on his machine. I'll comment steps in a sec

**Comment by jsmith** [comment]
I also updated my steps in the initial comment. Sorry they weren't as clear as they should have been!

**Comment by dsteen338** [comment]
This is how it went for me on Fedora, latest version

1. Install Intellij
2. Create a new project with the "Check out from version control"  and select the github option
3. Click the "create api token" and login
4. Hit next and select the SWE-4103-Group-3 repo and select clone
5. Checkout the branch
6. You will probably need to add the JDK as the project SDK
7. Build and run project

**Comment by brandon1024** [comment]
@dsteen338 you were able to start up the server?

**Comment by dsteen338** [comment]
Just got it working on macs windows machine. Needed an extra step after everything I said above

1. Open the "View" menu from the top toolbar
2. Click the "maven projects" button, the
3. Click the "Reimport all Maven Projects" button at the top of the maven projects view
4. Windows firewall will probably get mad because maven is trying to download stuff
5. Click allow on any prompts windows gives you
6. Let maven download the items and build

Project should now be able to launch.

**Comment by dsteen338** [comment]
@brandon1024 Yes I could launch and connect to local host.

**Pull request merged**
