### PR TITLE
Issue and PR Template

### PR DESCRIPTION
**Pull request by brandon1024**
### Changes Proposed in this Pull Request:
- Added Issue and PR template files, which are automatically put in the description field for new issues and pull requests. This should help keep issue and pull request descriptions full and consistent.

### Additional Comments and Documentation:
https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by dsteen338** [comment]
Should we have some Predefined tasks such as "Add Tests" or something like that?

**Comment by brandon1024** [comment]
We could, but that should be assumed. I can add it if you’d like though :)

**Comment by dsteen338** [comment]
You're right, it should be fine.

**Review by dsteen338 — APPROVED** [review]
Seems good to me.

**Pull request merged**
